name: vklib
description: Simple framework for dart allows you to use the VK API easily.
version: 0.3.0
homepage: https://github.com/Waitrum/VkLib
issue_tracker: https://github.com/Waitrum/VkLib/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  dotenv: ^4.1.0
#  logger: ^1.0.0

dev_dependencies:
  test: ^1.14.4
